spring:
  datasource:
#    url: jdbc:postgresql://post-gres-sql-db/postgres
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: password
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

##If want to see very extensive logging
#spring.jpa.properties.hibernate.generate_statistics=true
#logging.level.org.hibernate.type=trace
#logging.level.org.hibernate.stat=debug
v2solve:    
  app:
    security:
      xframe-option: none
      cors:        allowed-methods:        - "*"
        allowed-origins:        - "*"
        allowed-headers:        - "*"
      authwhitelist: "/oidc-support**"
      disable: true
      
logging:  level:    com:
      v2solve:
        app:
          security: INFO
server:
  port: 8080